### ISSUE TITLE
independent articles with table of contents and next/previous navigation

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/how-to-egghead#11]
currently, both the reviewer and instructor guides are single pages supported by anchor links with. We want to deliver independent article pages for each section.

* `/instructors` is a table of contents for the instructor guide.
* `/instructors/{SLUG}` are individual articles. The slug is the filename of the markdown, minus the extension. 
* `/reviewers` is a table of contents for lesson review articles.
* `/reviewers/{SLUG}` are individual articles. The slug is the filename of the markdown, minus the extension. 

Articles can be in a sequence if they are in the table of contents for the respective sections. Articles in a sequence should have appropriate `next` and `previous` style navigation.

The Table of Contents should be displayed alongside every article on the left-hand side.

**Comment by vojtaholik** [comment]
https://github.com/eggheadio/how-to-egghead/pull/37 should resolve this issue with slight difference: 
- all articles live under `/{slug}` - instead of `/reviewers/{slug}` or `/instructors/{slug}` 

can change if needed.
