### ISSUE TITLE
Bad Links and Missing Content

### ISSUE THREAD

**Issue by tayiorbeii** [eggheadio/how-to-egghead#7]
### Migrate away from Paper
* https://paper.dropbox.com/doc/01-Why-be-an-instructor-u68jBYc1Ly1F5wWoi4jXT
* https://paper.dropbox.com/doc/02-How-to-structure-your-course-YfYDW8HSjx7DsAEShXc4X
* https://paper.dropbox.com/doc/03-Record-your-lesson-5sBpHCVOxhPhlZYEVxrhY
* https://paper.dropbox.com/folder/show/04-Screencasting-tips-e.1gg8YzoPEhbTkrhvQwJ2zz3VfffmW8lGwgJoc5jCIvamKrIozeHB
* https://paper.dropbox.com/doc/07-Speak-concisely-v5Rk1EjXfhwrri6cRuPGA

### Dead Files
* https://www.dropbox.com/s/a5ahcas02qtxu99/egghead-edit-with-ripple-delete.mp4?dl=0
* https://www.dropbox.com/s/cyy9swbl3ga38kd/egghead-record-one-thought-at-a-time.mp4?dl=0
* https://www.dropbox.com/s/r6lu0h49v9sbfh3/01-egghead-react-introducing-advanced-react-component-patterns.mp4?dl=0
* https://www.dropbox.com/s/izvlyf41j6kk6kw/egghead-guide-their-eyes.mp4?dl=0
* https://www.dropbox.com/s/6x6o608fwiwv28b/egghead-avoid-intros-and-outros.mp4?dl=0
* https://www.dropbox.com/s/5fxdwvnttkxb2lr/egghead-show-then-maybe-explain.mp4?dl=0
* https://www.dropbox.com/s/2p6opnh0qn8r9ao/egghead-stay-on-topic.mp4?dl=0

### Lesson requires membership:
* https://egghead.io/lessons/react-creating-a-component-with-react-on-rails

### Images and Illustrations
* There are a lot of `[Put a picture here]` notes to do something about

**Comment by joelhooks** [comment]
placeholders are 100% fine, but we also have the ability to embed now, so we should do that where possible

@johnlindquist had an idea about building out exercises. His initial thought was "spot the flaws in this lesson". I'm not 100% on that specific exercise, but the idea of giving them exercises is interesting.

**Comment by vojtaholik** [comment]
@tayiorbeii is this issue still relevant?
